# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: edd029b5ecacc6a2238ff40f137ee410dc6075141647b66be64c2c4c6fc110db9babbe9863f98bdb12ea8a0098c856cec45a0159f19b55e82a67d5545db17031

test:
  secret_key_base: 05f219eb3fed08849349f611fdff88e37b73dae15ad5ce922bf0b64cd79dd5dfcc2afd59925c0e4db1bf20fefe92bad9b193a2c19492e92a83855331d0241624

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
